### ISSUE TITLE
Suprnova support

### ISSUE THREAD

**Issue by gradinkov** [gradinkov/rudehash#11]
No other big pools support direct coin mining anyway.

- [x] move coin server and port definitions from $Coins to $Pools
- [x] use $Pools[$Config.Pool].$Coins.length instead of $Pools[$Config.Pool].CoinMode
- [x] add $Pools[$Config.Pool].$Coins.Keys.Algo to pool algo list 
- [x] extend Test-Compatibility to check coin algos, and don't fail if pool algos are missing
- [x] add Suprnova definitions
- [x] add worker password support as Suprnova requires that

**Comment by Artanisx** [comment]
I second this, please add Suprnova support :) It was added on 3.0 milestone, but we're in 4.0 and no support for this pool is available :)

**Comment by gradinkov** [comment]
Yeah, milestones aren't managed properly these days :) Which coins are you most interested in?

**Comment by Artanisx** [comment]
I would love BTCP support on [Suprnova](https://btcp.suprnova.cc/) :)

**Comment by gradinkov** [comment]
Thanks! In the meanwhile, you could give zpool a try, BTCP is their only coin on the equihash pool right now.

**Comment by Artanisx** [comment]
I'll check it out, thank you :)

**Comment by gradinkov** [comment]
It should be working fine, please test and report back!

**Comment by Artanisx** [comment]
Will do, thanks :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-07 1:01 GMT+01:00 gradinkov <notifications@github.com>:
