### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by gradinkov** [gradinkov/rudehash#71]
Here's the example structure of a current JSON (there's more settings in real life, but this is just for demonstration):

~~~~
{
  "Worker": "desktop",
  "Coin": "zec",
  "Pool": "suprnova",
  "Miner": "dstm"
}
~~~~

This could be changed to something like this:

~~~~
[
  {
    "id": 1,
    "Worker": "desktop",
    "Coin": "zec",
    "Pool": "suprnova",
    "Miner": "dstm"
  }
]
~~~~

And then a "multi-profile" config would look like:

~~~~
[
  {
    "id": 1,
    "Worker": "desktop",
    "Coin": "zec",
    "Pool": "suprnova",
    "Miner": "dstm"
  },
  {
    "id": 2,
    "Worker": "desktop",
    "Coin": "btcp",
    "Pool": "suprnova",
    "Miner": "excavator"
  }
]
~~~~

If there's only one, RH would just start mining as it does now. But if RH detects that there's more than 1 profile, it'd ask the user to select one.

Now the only question that remains is, how well does PowerShell's ConvertTo/From-Json handle this.

**Comment by gradinkov** [comment]
An alternative option would be a command line argument to point to a different JSON file.

**Comment by gradinkov** [comment]
Useful links:

https://jsonformatter.curiousconcept.com/
https://jsoneditoronline.org/

**Comment by gradinkov** [comment]
~~~~
{
  "ActiveProfile":2,
  "Profiles":
  [
    {
      "Worker":"desktop",
      "Coin":"zec",
      "Pool":"suprnova",
      "Miner":"dstm"
    },
    {
      "Worker":"desktop",
      "Coin":"btcp",
      "Pool":"suprnova",
      "Miner":"excavator"
    }
  ]
}
~~~~

**Comment by gradinkov** [comment]
Quick solution:

~~~~
{
  "ActiveProfile":0,
  "Profiles":[
    {
      "Pool":"zpool",
      "Algo":"equihash",
      "Coin":"",
      "Miner":"dstm",
      "Worker":"rudehash",
      "Currency":"USD",
      "ElectricityCost":0.1,
      "Watchdog":true,
      "Debug":false,
      "MonitoringKey":"",
      "MphApiKey":"",
      "Wallet":"1HFapEBFTyaJ74SULTJ5oN5BK3C5AYHWzk",
      "WalletIsAltcoin":false,
      "User":"",
      "Region":"",
      "ExtraArgs":""
    },
    {
      "Pool":"zergpool",
      "Algo":"hsr",
      "Coin":"",
      "Miner":"hsrminer-hsr",
      "Worker":"rudehash",
      "Currency":"USD",
      "ElectricityCost":0.1,
      "Watchdog":false,
      "Debug":true,
      "MonitoringKey":"",
      "MphApiKey":"",
      "Wallet":"1HFapEBFTyaJ74SULTJ5oN5BK3C5AYHWzk",
      "WalletIsAltcoin":false,
      "User":"",
      "Region":"",
      "ExtraArgs":""
    }
  ]
}
~~~~

Final, preferred form:

~~~~
{
  "Debug":false,
  "Worker":"rudehash",
  "Currency":"USD",
  "ElectricityCost":0.1,
  "MonitoringKey":"",
  "MphApiKey":"",
  "ActiveProfile":0,
  "Profiles":[
    {
      "Pool":"zpool",
      "Algo":"equihash",
      "Coin":"",
      "Miner":"dstm",
      "Watchdog":true,
      "Wallet":"1HFapEBFTyaJ74SULTJ5oN5BK3C5AYHWzk",
      "WalletIsAltcoin":false,
      "User":"",
      "Region":"",
      "ExtraArgs":""
    },
    {
      "Pool":"zergpool",
      "Algo":"hsr",
      "Coin":"",
      "Miner":"hsrminer-hsr",
      "Watchdog":false,
      "Wallet":"1HFapEBFTyaJ74SULTJ5oN5BK3C5AYHWzk",
      "WalletIsAltcoin":false,
      "User":"",
      "Region":"",
      "ExtraArgs":""
    }
  ]
}
~~~~

**Comment by gradinkov** [comment]
Config generator + validator is ready. Now "all" that's left is actually using it that way. It seems there's a totally 1:1 match between JSON arrays/hashtables and PS arrays/hashtables so it should be pretty doable.

Certain keys will be on different levels, that's a change.

Gotta decide if I want to request user input on the active profile, or just use the JSON option. Hmm...

**Comment by gradinkov** [comment]
Or maybe, just maybe, it could be another config option lol. `AskForProfile` or something. If having such an option, gotta make sure that there's a timeout, otherwise mining will stop after a restart. Make sure to update ActiveProfile after each startup. Also do some pretty-print / format-table for the profiles.

~~FRW/compatcheck will not cover adding new profiles on top of the current one.~~ done, only checks selected profile

~~Also gotta figure out indexing, config generator starts at 1!~~ done, indexes are shifted

~~Will have to test if PowerShell reorders profiles, coz then we're in trouble. Then we gotta add an ID field and do some stupid lookups instead of direct indexing. But this will make validation way more difficult. Would prefer some sort of manual enforced sorting.~~ Arraylists are not reordered apparently.

**Comment by bviktor** [comment]
Select all when clicking in the json textarea

**Comment by gradinkov** [comment]
~~Select all when clicking in the json textarea~~ done

**Comment by gradinkov** [comment]
~~Generate uuid from js~~ done

**Comment by gradinkov** [comment]
Add to website for easy access? Or do installer, then we can have nice shortcuts.

**Comment by gradinkov** [comment]
Website is yes and no, it's neat to have, but it'll always validate against the latest schema, while the user may not have that. Prolly go the installer route, it has a lot of benefits.

**Comment by gradinkov** [comment]
I'll leave `AskForProfile` for now.
